server:
  port: ${PORT:7074}


spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 8d408ff76b1915728870
#            clientSecret: 9403a4ccbd62a8f71ddd21da51abd41531e14bb2

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

