server:
  port: ${PORT:7074}


spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 275467666884234
            clientSecret: 18c6977e20cb1374b2085df443aa684d

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

